-- Phase 3: PO CSV Staging Infrastructure.
-- Creates persistent (not TEMP) staging tables for bulk PO CSV imports.
-- Nothing here reaches the official ledger (purchase_orders/po_line_items/
-- inventory_movements/grn_receipts/discrepancy_notes/debit_notes) --
-- staging, validation, and master-product resolution only. Review and
-- posting are later phases. See PROJECT_HANDOFF.md and po_csv_staging.py.
--
-- Idempotent -- safe to run more than once (CREATE TABLE/INDEX IF NOT
-- EXISTS throughout; no existing table is altered, so there's no
-- backfill/constraint-guard complexity like migrations 001/002 needed).
--
-- Apply with:
--   /opt/homebrew/opt/postgresql@16/bin/psql drizzl_inventory -f migrations/003_po_csv_staging.sql

BEGIN;

-- Phase 3 (2026-08-15): PO CSV staging infrastructure. Staged data never
-- reaches the official ledger (purchase_orders/po_line_items/
-- inventory_movements etc.) -- see po_csv_staging.py and
-- migrations/003_po_csv_staging.sql. Review/posting is a later phase.

-- One row per uploaded CSV file. file_sha256 + customer_id gives exact-
-- file idempotency: re-uploading the identical bytes for the same
-- customer reuses this batch rather than creating a duplicate.
CREATE TABLE IF NOT EXISTS po_import_batches (
    batch_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     INTEGER NOT NULL REFERENCES customers(id),
    source_filename TEXT NOT NULL,
    file_sha256     TEXT NOT NULL,
    source_entity   TEXT,
    status          TEXT NOT NULL DEFAULT 'staged',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (customer_id, file_sha256)
);
CREATE INDEX IF NOT EXISTS idx_po_import_batches_customer_id ON po_import_batches(customer_id);
CREATE INDEX IF NOT EXISTS idx_po_import_batches_created_at ON po_import_batches(created_at);

-- Every readable CSV row, before any normalization -- raw_data preserves
-- exactly what the source file said, so nothing is ever lost even if a
-- field is malformed or a SKU is unknown.
CREATE TABLE IF NOT EXISTS po_import_rows (
    row_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id           BIGINT NOT NULL REFERENCES po_import_batches(batch_id),
    source_row_number  INTEGER NOT NULL,
    raw_data           JSONB NOT NULL,
    validation_status  TEXT NOT NULL DEFAULT 'valid',
    validation_errors  JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (batch_id, source_row_number)
);
CREATE INDEX IF NOT EXISTS idx_po_import_rows_batch_id ON po_import_rows(batch_id);

-- One row per (customer, PoNumber) within a batch -- the CSV repeats
-- PO-level fields on every product line, so many po_import_rows collapse
-- into one staged PO here. source_location_id is deliberately NULL on
-- import (see po_csv_staging.py) -- never inferred from the customer's
-- destination facility, a completely different concept from a Drizzl
-- location (see destination_facility_* below).
CREATE TABLE IF NOT EXISTS staged_purchase_orders (
    staged_po_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                   BIGINT NOT NULL REFERENCES po_import_batches(batch_id),
    customer_id                INTEGER NOT NULL REFERENCES customers(id),

    external_po_number         TEXT NOT NULL,

    entity_raw                 TEXT,
    -- The CUSTOMER's receiving facility -- e.g. "DEMO FACILITY A", Mumbai. NOT a
    -- Drizzl location. Never used to infer source_location_id.
    destination_facility_id    TEXT,
    destination_facility_name  TEXT,
    destination_city           TEXT,

    po_created_at              TIMESTAMP,
    po_modified_at             TIMESTAMP,
    external_status            TEXT,
    supplier_code               TEXT,
    vendor_name                 TEXT,

    po_amount                   NUMERIC,
    expected_delivery_date      DATE,
    po_expiry_date               DATE,
    otb_reference_number          TEXT,
    internal_external_po           TEXT,
    po_ageing                       INTEGER,
    brand_name                       TEXT,
    reference_po_number               TEXT,

    -- The Drizzl warehouse that will fulfill this order. Always NULL on
    -- initial staging -- assigned by a human in Phase 4, never guessed
    -- from destination_facility_id/destination_facility_name/
    -- destination_city or any other field.
    source_location_id          INTEGER REFERENCES locations(id),

    validation_status            TEXT NOT NULL DEFAULT 'valid',
    validation_errors            JSONB NOT NULL DEFAULT '[]'::jsonb,

    created_at                    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (batch_id, customer_id, external_po_number)
);
CREATE INDEX IF NOT EXISTS idx_staged_pos_batch_id ON staged_purchase_orders(batch_id);
CREATE INDEX IF NOT EXISTS idx_staged_pos_customer_external_po ON staged_purchase_orders(customer_id, external_po_number);
CREATE INDEX IF NOT EXISTS idx_staged_pos_validation_status ON staged_purchase_orders(validation_status);
CREATE INDEX IF NOT EXISTS idx_staged_pos_source_location_id ON staged_purchase_orders(source_location_id);

-- One row per raw CSV product line -- deliberately no UNIQUE(staged_po_id,
-- external_sku), since a future export may legitimately repeat a SKU on
-- the same PO. product_id is resolved through catalog.resolve_customer_sku()
-- at staging time -- NULL means the customer's SKU didn't map to a known
-- Drizzl master product (never guessed, never auto-created).
CREATE TABLE IF NOT EXISTS staged_po_lines (
    staged_line_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staged_po_id              BIGINT NOT NULL REFERENCES staged_purchase_orders(staged_po_id),
    raw_row_id                 BIGINT NOT NULL UNIQUE REFERENCES po_import_rows(row_id),
    source_row_number           INTEGER NOT NULL,

    external_sku                 TEXT,
    external_sku_description      TEXT,

    -- Resolved via catalog.resolve_customer_sku(), never legacy
    -- products.sku_code -- the customer's SKU must never become our true
    -- product identity. NULL + validation_status='blocked' if unmapped.
    product_id                     INTEGER REFERENCES master_products(product_id),

    category_id                     TEXT,

    ordered_qty                       NUMERIC,
    received_qty                       NUMERIC,
    balanced_qty                         NUMERIC,

    tax                                   NUMERIC,
    line_value_without_tax                  NUMERIC,
    line_value_with_tax                       NUMERIC,
    mrp                                         NUMERIC,
    unit_based_cost                               NUMERIC,

    validation_status                              TEXT NOT NULL DEFAULT 'valid',
    validation_errors                                JSONB NOT NULL DEFAULT '[]'::jsonb,

    created_at                                        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_staged_po_lines_staged_po_id ON staged_po_lines(staged_po_id);
CREATE INDEX IF NOT EXISTS idx_staged_po_lines_product_id ON staged_po_lines(product_id);
CREATE INDEX IF NOT EXISTS idx_staged_po_lines_external_sku ON staged_po_lines(external_sku);
CREATE INDEX IF NOT EXISTS idx_staged_po_lines_validation_status ON staged_po_lines(validation_status);

COMMIT;
