-- Phase 6: GRN CSV staging + raw-row preservation + safe normalization +
-- canonical verification against the official PO.
--
-- Analogous to Phase 3 (PO CSV staging), but for GRNs. Creates ZERO
-- official-ledger effect -- no grn_receipts/grn_line_items/
-- inventory_movements are touched by anything in this migration or the
-- module it supports (grn_csv_staging.py). See TECHNICAL_README.md.
--
-- validation_status/validation_errors on staged_grns/staged_grn_lines
-- describe problems intrinsic to the imported data itself (parsing,
-- normalization, unmapped SKUs) -- set once at staging time.
-- po_verification_status/po_verification_errors on staged_grns describe
-- whether the normalized GRN agrees with an official PO -- recomputed
-- any time via grn_csv_staging.validate_staged_grn()/revalidate_grn_batch(),
-- independently of the intrinsic findings, so a GRN staged before its PO
-- exists can be revalidated later without redoing normalization.
--
-- Idempotent -- safe to run more than once (CREATE TABLE/INDEX IF NOT
-- EXISTS throughout; nothing here alters an existing table).
--
-- Apply with:
--   /opt/homebrew/opt/postgresql@16/bin/psql drizzl_inventory -f migrations/005_grn_csv_staging.sql

BEGIN;

-- One row per uploaded GRN CSV file. Unlike the PO CSV, this export does
-- NOT identify the customer/buyer anywhere in its own data (VendorName/
-- SupplierCode identify the SUPPLIER, i.e. Drizzl) -- customer_id must
-- always be supplied explicitly by the caller, never inferred. Same
-- exact-file idempotency pattern as po_import_batches.
CREATE TABLE IF NOT EXISTS grn_import_batches (
    batch_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     INTEGER NOT NULL REFERENCES customers(id),
    source_filename TEXT NOT NULL,
    file_sha256     TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'staged',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (customer_id, file_sha256)
);
CREATE INDEX IF NOT EXISTS idx_grn_import_batches_customer_id ON grn_import_batches(customer_id);
CREATE INDEX IF NOT EXISTS idx_grn_import_batches_created_at ON grn_import_batches(created_at);

-- Every readable CSV row, before any normalization -- raw_data preserves
-- exactly what the source file said. A malformed value or unknown SKU
-- never silently drops a row, only flags it.
CREATE TABLE IF NOT EXISTS grn_import_rows (
    row_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id           BIGINT NOT NULL REFERENCES grn_import_batches(batch_id),
    source_row_number  INTEGER NOT NULL,
    raw_data           JSONB NOT NULL,
    validation_status  TEXT NOT NULL DEFAULT 'valid',
    validation_errors  JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (batch_id, source_row_number)
);
CREATE INDEX IF NOT EXISTS idx_grn_import_rows_batch_id ON grn_import_rows(batch_id);

-- One row per (customer, GrnNumber) within a batch -- the CSV repeats
-- GRN-level fields on every product/lot line, so many raw rows collapse
-- into one staged GRN header here. NOT globally unique on
-- (customer_id, external_grn_number) -- a corrected/re-exported file may
-- legitimately contain the same GRN number again in a later batch; that
-- is a duplicate/conflict to detect (po_verification_status), not
-- something ingestion itself should refuse to store.
CREATE TABLE IF NOT EXISTS staged_grns (
    staged_grn_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                BIGINT NOT NULL REFERENCES grn_import_batches(batch_id),
    customer_id             INTEGER NOT NULL REFERENCES customers(id),

    external_grn_number     TEXT NOT NULL,
    external_po_number      TEXT,
    -- The official PO this GRN was matched against, resolved via
    -- purchase_orders.py's customer-scoped exact lookup -- never a stub,
    -- never fuzzy/prefix matched. NULL until/unless a matching official
    -- PO is found. See grn_csv_staging.validate_staged_grn().
    official_po_id          BIGINT REFERENCES purchase_orders(po_id),

    facility_name           TEXT,
    supplier_code           TEXT,
    vendor_name              TEXT,

    invoice_number            TEXT,
    invoice_date               DATE,
    external_created_at         TIMESTAMP,

    -- Blank is allowed and common (a rejection can exist with no DN
    -- issued yet). Multiple DISTINCT nonblank DN numbers within one GRN
    -- is a validation_status='blocked' condition -- never inferred/
    -- invented from DNQuantity being nonzero.
    dn_number                    TEXT,

    validation_status             TEXT NOT NULL DEFAULT 'valid',
    validation_errors             JSONB NOT NULL DEFAULT '[]'::jsonb,

    -- Independent of validation_status/validation_errors above --
    -- recomputed any time via validate_staged_grn()/revalidate_grn_batch()
    -- without touching the intrinsic parsing/normalization findings.
    po_verification_status         TEXT NOT NULL DEFAULT 'pending',
    po_verification_errors          JSONB NOT NULL DEFAULT '[]'::jsonb,

    created_at                       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (batch_id, customer_id, external_grn_number)
);
CREATE INDEX IF NOT EXISTS idx_staged_grns_batch_id ON staged_grns(batch_id);
CREATE INDEX IF NOT EXISTS idx_staged_grns_customer_external_grn ON staged_grns(customer_id, external_grn_number);
CREATE INDEX IF NOT EXISTS idx_staged_grns_customer_external_po ON staged_grns(customer_id, external_po_number);
CREATE INDEX IF NOT EXISTS idx_staged_grns_official_po_id ON staged_grns(official_po_id);
CREATE INDEX IF NOT EXISTS idx_staged_grns_validation_status ON staged_grns(validation_status);
CREATE INDEX IF NOT EXISTS idx_staged_grns_po_verification_status ON staged_grns(po_verification_status);

-- One row per normalized PHYSICAL receipt/lot line -- NOT necessarily one
-- raw CSV row (see staged_grn_line_source_rows and grn_csv_staging.py's
-- normalization algorithm). Deliberately no UNIQUE(staged_grn_id,
-- external_sku): the same SKU can legitimately appear as more than one
-- real lot (different LotExpiryDate/received_qty) within one GRN.
CREATE TABLE IF NOT EXISTS staged_grn_lines (
    staged_grn_line_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staged_grn_id               BIGINT NOT NULL REFERENCES staged_grns(staged_grn_id),

    external_sku                TEXT,
    external_sku_description    TEXT,
    -- Resolved via catalog.resolve_customer_sku(), never legacy
    -- products.sku_code. NULL + validation_status='blocked' if unmapped.
    product_id                  INTEGER REFERENCES master_products(product_id),

    brand_name                  TEXT,
    category                    TEXT,

    -- The quantity that will eventually reduce inventory -- never
    -- expected_qty (this CSV has no such column) and never summed across
    -- raw rows that are really the same physical line represented twice
    -- (see the normalization algorithm).
    received_qty                NUMERIC,

    -- Source rejection facts, preserved but NOT the source of truth for
    -- the PO-vs-GRN commitment discrepancy (that's ordered_qty -
    -- received_qty, computed in get_grn_po_comparison()).
    dn_quantity                 NUMERIC,
    dn_value                    NUMERIC,

    grn_line_value_without_tax  NUMERIC,
    grn_line_value_with_tax     NUMERIC,

    lot_mrp                     NUMERIC,
    lot_expiry_date             DATE,

    cgst_rate        NUMERIC,
    cgst_amount      NUMERIC,
    sgst_rate        NUMERIC,
    sgst_amount      NUMERIC,
    igst_rate        NUMERIC,
    igst_amount      NUMERIC,
    cess_rate        NUMERIC,
    cess_amount      NUMERIC,
    additional_cess  NUMERIC,
    total_tax        NUMERIC,
    total_amount     NUMERIC,

    validation_status           TEXT NOT NULL DEFAULT 'valid',
    validation_errors           JSONB NOT NULL DEFAULT '[]'::jsonb,

    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_staged_grn_lines_staged_grn_id ON staged_grn_lines(staged_grn_id);
CREATE INDEX IF NOT EXISTS idx_staged_grn_lines_product_id ON staged_grn_lines(product_id);
CREATE INDEX IF NOT EXISTS idx_staged_grn_lines_external_sku ON staged_grn_lines(external_sku);
CREATE INDEX IF NOT EXISTS idx_staged_grn_lines_validation_status ON staged_grn_lines(validation_status);

-- Raw row <-> normalized line lineage. One normalized line can derive
-- from more than one raw row (the duplicated-DN-representation case);
-- UNIQUE(raw_row_id) ensures a given raw row is never claimed by more
-- than one normalized line.
CREATE TABLE IF NOT EXISTS staged_grn_line_source_rows (
    staged_grn_line_id BIGINT NOT NULL REFERENCES staged_grn_lines(staged_grn_line_id),
    raw_row_id          BIGINT NOT NULL REFERENCES grn_import_rows(row_id),
    PRIMARY KEY (staged_grn_line_id, raw_row_id),
    UNIQUE (raw_row_id)
);

COMMIT;
