ALTER TABLE inventory_movements ADD COLUMN IF NOT EXISTS source_grn_id BIGINT REFERENCES grn_receipts(grn_id);

CREATE TABLE IF NOT EXISTS discrepancy_import_batches (
    batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id),
    source_filename TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (customer_id, file_sha256)
);

CREATE TABLE IF NOT EXISTS staged_discrepancy_lines (
    staged_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES discrepancy_import_batches(batch_id),
    source_row_number INTEGER NOT NULL,
    raw_data JSONB NOT NULL,
    pr_number TEXT,
    po_number TEXT,
    grn_number TEXT,
    external_sku TEXT,
    product_id INTEGER REFERENCES master_products(product_id),
    accepted_qty NUMERIC,
    rejected_qty NUMERIC,
    rejected_reason TEXT,
    official_grn_id BIGINT REFERENCES grn_receipts(grn_id),
    discrepancy_movement_id INTEGER REFERENCES inventory_movements(id),
    review_status TEXT NOT NULL,
    review_message TEXT,
    classified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (batch_id, source_row_number)
);
CREATE INDEX IF NOT EXISTS idx_staged_discrepancy_batch ON staged_discrepancy_lines(batch_id);
CREATE INDEX IF NOT EXISTS idx_staged_discrepancy_grn ON staged_discrepancy_lines(grn_number);
